### ISSUE TITLE
Movement gets stuck

### ISSUE THREAD

**Issue by xHybred** [captainzero93/AHK-cs2-Null-Movement-Snap-Tap-SOCD#1]
Sometimes randomly when I'm using the script I'll get stuck still until I press the key again. like if I just pressed A then I press D I can't move until I press A again. It happens randomly when I'm just playing Call of Duty

**Comment by captainzero93** [comment]
I'll have a look and try to fix that issue later

**Comment by captainzero93** [comment]
> Sometimes randomly when I'm using the script I'll get stuck still until I press the key again. like if I just pressed A then I press D I can't move until I press A again. It happens randomly when I'm just playing Call of Duty

I've updated the script, please try again and let me know if you still have any problems

**Comment by xHybred** [comment]
Yeah theirs on very major issue and that is with this new script I cant move at all now lol. WASD doesnt work

**Comment by xHybred** [comment]
Yeah theirs on very major issue and that is with this new script I cant move at all now lol. WASD doesnt work

[ahk_debug.txt](https://github.com/user-attachments/files/16418754/ahk_debug.txt)
[ahk_log.txt](https://github.com/user-attachments/files/16418755/ahk_log.txt)

**Comment by captainzero93** [comment]
> Yeah theirs on very major issue and that is with this new script I cant move at all now lol. WASD doesnt work, thanks for the debug information, just got a few projects on right now
> 
> [ahk_debug.txt](https://github.com/user-attachments/files/16418754/ahk_debug.txt) [ahk_log.txt](https://github.com/user-attachments/files/16418755/ahk_log.txt)


I will revert it for now and try again at some point

**Comment by captainzero93** [comment]
Try again now , I have updated the  code

**Comment by captainzero93** [comment]
tested, fixed, closing report unless further issues are detected

**Comment by xHybred** [comment]
Still happening, but now it happens with the W and S key as well


is it bad or just q short thing that happens for a moment or two? AHK is having to do a lot here,o I can try again but it DOES work for snap tap like peeking etc I tested it
